// GENERATED FILE — do not edit by hand.
//
// The vocabulary comes from two Notion databases under "Elements of Music —
// Vocabulary": **Vocabulary Fields** (the shape — one row per sub-list, with
// its concept, its stable field id and its position) and **Vocabulary Terms**
// (the words — one row is one word, related to its field, ticked if it tags
// itself, with any alternative spellings). The concepts, their order and the
// eight hues come from scripts/sync-vocabulary.mjs. Change a word in Notion,
// or the shape in that script, then run:
//
//   npm run sync:vocab
//
// See lib/musicElements.ts for what ELEMENTS feeds, and lib/propertyTags.ts
// for what AUTO_TERMS, ALIASES and GLOSSARY do.
import type { ElementCategory } from './musicElements'

export const ELEMENTS: ElementCategory[] = [
  {
    id: 'pitch',
    color: '#f87171',
    label: 'Pitch',
    fields: [
      {
        id: 'pitch.element',
        label: 'Element name',
        options: ['Melodic', 'Melody', 'Pitch'],
        allowCustom: true,
      },
      {
        id: 'pitch.contour',
        label: 'Melodic motion & contour',
        options: [
          'Angular',
          'Arc-shaped',
          'Ascending',
          'Conjunct',
          'Contour',
          'Contrary motion',
          'Descending',
          'Disjunct',
          'Florid',
          'Leap',
          'Parallel motion',
          'Sequence',
          'Sequential',
          'Similar motion',
          'Smooth',
          'Static',
          'Stepwise',
          'Virtuosic',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.range',
        label: 'Range & register',
        options: [
          'High register',
          'Limited range',
          'Low register',
          'Narrow range',
          'Register extremes',
          'Tessitura',
          'Wide range',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.tonality',
        label: 'Tonality',
        options: [
          'Bitonal',
          'Chromatic',
          'Chromaticism',
          'Diatonic',
          'Major',
          'Minor',
          'Modal',
          'Modality',
          'Modulating',
          'Picardy 3rd',
          'Polytonal',
          'Tierce de picardie',
          'Tonal',
          'Tonal ambiguity',
          'Tonal centre',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.scale',
        label: 'Scale / mode type',
        options: [
          'Aeolian',
          'Chromatic scale',
          'Dorian',
          'Harmonic minor',
          'Mixolydian',
          'Pentatonic',
          'Phrygian',
          'Scale-based',
          'Scalic',
          'Whole-tone',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.harmony',
        label: 'Harmony & chord quality',
        options: [
          'Arpeggiated',
          'Augmented',
          'Block chords',
          'Broken chords',
          'Diminished',
          'Drone',
          'Inverted',
          'Major 7',
          'Open 5ths',
          'Pedal point',
          'Quartal',
          'Resolution',
          'Resolved',
          'Root position',
          'Suspended',
          'Suspension',
          'Tonic-and-dominant based',
          'Triadic',
          'Unresolved',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.consonance',
        label: 'Consonance / dissonance',
        options: [
          'Cluster-like',
          'Clusters',
          'Consonant',
          'Dissonance',
          'Dissonant',
          'Semitone dissonance',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.cadence',
        label: 'Cadence type',
        options: ['Cadential', 'Imperfect', 'Perfect'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'duration',
    color: '#eab308',
    label: 'Duration',
    fields: [
      {
        id: 'duration.element',
        label: 'Element name',
        options: [
          'Beat',
          'Duration',
          'Meter',
          'Metre',
          'Pulse',
          'Rhythm',
          'Rhythmic',
          'Tempo',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.tempo',
        label: 'Speed (tempo)',
        options: ['Fast', 'Lively', 'Quick', 'Rapid', 'Slow'],
        allowCustom: true,
      },
      {
        id: 'duration.tempoChange',
        label: 'Tempo change',
        options: ['Acceleration', 'Getting faster', 'Slowing'],
        allowCustom: true,
      },
      {
        id: 'duration.drive',
        label: 'Drive / momentum',
        options: [
          'Boisterous',
          'Busy',
          'Driving',
          'Energetic',
          'Momentum',
          'Perpetual',
          'Propelling',
          'Relentless',
          'Rhythmic drive',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.steadiness',
        label: 'Steadiness / regularity',
        options: [
          'Balanced',
          'Consistent',
          'Constant',
          'Continuous',
          'Even',
          'Maintained',
          'Pervasive',
          'Regular',
          'Steady',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.syncopation',
        label: 'Irregularity / syncopation',
        options: [
          'Ambiguous',
          'Cross-rhythm',
          'Displaced',
          'Hemiola',
          'Hemiolic',
          'Off-beat',
          'Polyrhythm',
          'Polyrhythmic',
          'Shifting',
          'Syncopated',
          'Uneven',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.metre',
        label: 'Metre & metre changes',
        options: [
          '11/8',
          '12/8',
          '2/2',
          '2/4',
          '3/2',
          '3/4',
          '3/8',
          '4/4',
          '5/4',
          '5/8',
          '6/4',
          '6/8',
          '7/4',
          '7/8',
          '9/8',
          'Alla breve',
          'Changing metre',
          'Common time',
          'Compound',
          'Cut common time',
          'Duple',
          'Mixed metre',
          'Multimetric',
          'Quadruple',
          'Simple triple',
          'Triple',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.values',
        label: 'Note-value character',
        options: [
          'Anacrusis',
          'Augmentation',
          'Augmented',
          'Diminution',
          'Dotted',
          'Duplet',
          'Long',
          'Quintuplet',
          'Sextuplet',
          'Short',
          'Shorter',
          'Snap',
          'Sustained',
          'Tied',
          'Triplet',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.feel',
        label: 'Rhythmic feel & character',
        options: ['Chant-like', 'Dance-like', 'Lilting', 'March-like', 'Stamping', 'Warlike'],
        allowCustom: true,
      },
      {
        id: 'duration.italian',
        label: 'Tempo & rhythmic terms (Italian)',
        options: [
          'Accelerando',
          'Allegretto grazioso',
          'Allegro',
          'Allegro Vivace',
          'Animando',
          'Leggierissimo',
          'Lento',
          'Lento maestoso',
          'Maestoso',
          'Metric modulation',
          'Moto perpetuo',
          'Rallentando',
          'Ritardando',
          'Ritenuto',
          'Rubato',
          'Senza misura',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'dynamics',
    color: '#22c55e',
    label: 'Dynamics',
    fields: [
      {
        id: 'dynamics.element',
        label: 'Element name',
        options: ['Dynamic', 'Dynamics', 'Loudness', 'Volume'],
        allowCustom: true,
      },
      {
        id: 'dynamics.volume',
        label: 'Dynamic level',
        options: ['ppp', 'pp', 'p', 'mp', 'mf', 'f', 'ff', 'fff'],
        allowCustom: true,
      },
      {
        id: 'dynamics.loudness',
        label: 'Loudness level',
        options: [
          'Forced',
          'Limited',
          'Loud',
          'Quiet',
          'Soft',
          'Softer',
          'Static (volume)',
          'Subtle',
          'Wide (dynamic range)',
        ],
        allowCustom: true,
      },
      {
        id: 'dynamics.change',
        label: 'Change in dynamics',
        options: [
          'Frequent',
          'Gradual',
          'Gradually',
          'Sudden',
          'Swelling',
          'Swells',
          'Terraced',
          'Varied',
        ],
        allowCustom: true,
      },
      {
        id: 'dynamics.italian',
        label: 'Dynamic markings (Italian)',
        options: [
          'Crescendo',
          'Decrescendo',
          'Diminuendo',
          'Dynamic letter levels (ppp–ff)',
          'Fortepiano (fp)',
          'Sforzando (sfz)',
          'Sfzp',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'expressive',
    color: '#84cc16',
    label: 'Expression',
    fields: [
      {
        id: 'expressive.element',
        label: 'Element name',
        options: ['Articulation', 'Expression', 'Expressive techniques', 'Phrasing'],
        allowCustom: true,
      },
      {
        id: 'expressive.articulation',
        label: 'Articulation',
        options: [
          'Accented',
          'Arco',
          'Detached',
          'Legato',
          'Marcato',
          'Pizzicato',
          'Slurred',
          'Slurs',
          'Staccatissimo',
          'Staccato',
          'Sustained',
          'Tenuto',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.technique',
        label: 'Special playing techniques',
        options: [
          'Bartók pizz.',
          'Col legno',
          'Glissandi',
          'Glissando',
          'Jeté bowing',
          'Laissez vibrer',
          'Slap tonguing',
          'Snap pizzicato',
          'Spiccato',
          'Sul ponticello',
          'Sul tasto',
          'Tremolo',
          'Trill',
          'Vibrato',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.phrasing',
        label: 'Phrasing & character',
        options: [
          'Animated (animando)',
          'Barbaric (feroce)',
          'Boisterous',
          'Delicate',
          'Dramatic',
          'Energetic',
          'Expressive',
          'Forceful',
          'Graceful',
          'Intense',
          'Languid',
          'Lyrical',
          'Majestic (maestoso)',
          'Playful',
          'Relentless',
          'Savage',
          'Sweet (dolce)',
          'Urgent',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.italian',
        label: 'Performance directions (Italian)',
        options: [
          '‘Breathing’ marks',
          'Ad libitum',
          'Cantabile',
          'Con forza',
          'Con sordino (mute)',
          'Delicatamente',
          'Dolce',
          'Espressivo',
          'Grazioso',
          'Leggierissimo',
          'Leggiero',
          'Semplice',
          'Senza misura',
          'Senza sordino',
          'Senza vibrato',
          'Sotto voce',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'media',
    color: '#60a5fa',
    label: 'Performing media',
    fields: [
      {
        id: 'media.element',
        label: 'Element name',
        options: [
          'Ensemble',
          'Forces',
          'Instrumentation',
          'Orchestration',
          'Performing media',
        ],
        allowCustom: true,
      },
      {
        id: 'media.instrument',
        label: 'Instrument / section',
        options: [
          'Basso continuo',
          'Brass',
          'Brass section',
          'Continuo',
          'Full orchestra',
          'Guitar',
          'Horn section',
          'Keyboard',
          'Percussion',
          'Percussion section',
          'Rhythm section',
          'Solo instrument',
          'String section',
          'Strings',
          'Synth / electronic',
          'Tutti',
          'Voice',
          'Wind section',
          'Winds',
          'Woodwind',
          'Woodwind section',
        ],
        allowCustom: true,
      },
      {
        id: 'media.strings',
        label: 'Strings',
        options: [
          'Acoustic guitar',
          'Banjo',
          'Bass guitar',
          'Cello',
          'Double bass',
          'Electric guitar',
          'Erhu',
          'Fiddle',
          'Guitar',
          'Harp',
          'Koto',
          'Lower strings',
          'Mandolin',
          'Sitar',
          'Ukulele',
          'Upper strings',
          'Viola',
          'Violin',
        ],
        allowCustom: true,
      },
      {
        id: 'media.woodwind',
        label: 'Woodwind',
        options: [
          'Alto flute',
          'Alto saxophone',
          'Baritone saxophone',
          'Bass clarinet',
          'Bassoon',
          'Clarinet',
          'Contrabassoon',
          'Cor anglais',
          'Didgeridoo',
          'Flute',
          'Oboe',
          'Pan pipes',
          'Piccolo',
          'Recorder',
          'Saxophone',
          'Shakuhachi',
          'Soprano saxophone',
          'Tenor saxophone',
        ],
        allowCustom: true,
      },
      {
        id: 'media.brass',
        label: 'Brass',
        options: [
          'Baritone horn',
          'Bass trombone',
          'Cornet',
          'Euphonium',
          'Flugelhorn',
          'French horn',
          'Horn',
          'Tenor horn',
          'Trombone',
          'Trumpet',
          'Tuba',
        ],
        allowCustom: true,
      },
      {
        id: 'media.percussion',
        label: 'Percussion',
        options: [
          'Anvil',
          'Bass drum',
          'Bongos',
          'Cajón',
          'Castanets',
          'Celesta',
          'Chimes',
          'Claves',
          'Congas',
          'Cowbell',
          'Crash cymbals',
          'Cymbals',
          'Djembe',
          'Drum kit',
          'Glockenspiel',
          'Gong',
          'Guiro',
          'Hi-hat',
          'Maracas',
          'Marimba',
          'Shaker',
          'Sleigh bells',
          'Snare drum',
          'Suspended cymbal',
          'Taiko',
          'Tam-tam',
          'Tambourine',
          'Temple blocks',
          'Timpani',
          'Triangle',
          'Tubular bells',
          'Vibraphone',
          'Whip',
          'Wind chimes',
          'Woodblock',
          'Xylophone',
        ],
        allowCustom: true,
      },
      {
        id: 'media.keyboard',
        label: 'Keyboard',
        options: [
          'Accordion',
          'Clavichord',
          'Electric piano',
          'Harmonium',
          'Harpsichord',
          'Organ',
          'Piano',
          'Pipe organ',
          'Synthesiser',
          'Synthesizer',
        ],
        allowCustom: true,
      },
      {
        id: 'media.voice',
        label: 'Voice',
        options: [
          'Alto',
          'Backing vocals',
          'Baritone',
          'Bass',
          'Chorus',
          'Contralto',
          'Countertenor',
          'Falsetto',
          'Lead vocal',
          'Mezzo-soprano',
          'Soprano',
          'Spoken word',
          'Sprechstimme',
          'Tenor',
          'Treble',
          'Vocalise',
        ],
        allowCustom: true,
      },
      {
        id: 'media.ensemble',
        label: 'Ensemble / forces',
        options: [
          'A cappella',
          'Big band',
          'Chamber ensemble',
          'Choir',
          'Concert band',
          'Duet',
          'Orchestra',
          'Quartet',
          'Quintet',
          'Rock band',
          'Solo',
          'String orchestra',
          'Trio',
          'Vocal ensemble',
        ],
        allowCustom: true,
      },
      {
        id: 'media.production',
        label: 'Sound produced by',
        options: ['Blowing', 'Bowing', 'Electronic', 'Plucking', 'Singing', 'Striking'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'timbre',
    color: '#22d3ee',
    label: 'Timbre',
    fields: [
      {
        id: 'timbre.element',
        label: 'Element name',
        options: ['Sound quality', 'Timbre', 'Tone color', 'Tone colour'],
        allowCustom: true,
      },
      {
        id: 'timbre.bright',
        label: 'Bright / brilliant',
        options: [
          'Bright',
          'Brilliant',
          'Clear',
          'Crisp',
          'Glittering',
          'Ringing',
          'Shimmering',
          'Sparkling',
          'Vibrant',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.warm',
        label: 'Warm / mellow / smooth',
        options: [
          'Cantabile',
          'Ethereal',
          'Even',
          'Floating',
          'Fluid',
          'Gentle',
          'Lyrical',
          'Mellow',
          'Sweet',
          'Warm',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.dark',
        label: 'Dark / dull / heavy',
        options: ['Dark', 'Dull', 'Heavy', 'Hollow', 'Muted', 'Subdued'],
        allowCustom: true,
      },
      {
        id: 'timbre.harsh',
        label: 'Harsh / strident / forceful',
        options: [
          'Acute',
          'Brittle',
          'Forceful',
          'Harsh',
          'Intense',
          'Relentless',
          'Strident',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.material',
        label: 'Material / sound-source',
        options: [
          'Bell-like',
          'Dry',
          'Echoey',
          'Metallic',
          'Nasal',
          'Percussive',
          'Resonant',
          'Wooden',
          'Woody',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.mood',
        label: 'Mood / character',
        options: ['Delicate', 'Dramatic', 'Eerie', 'Languid', 'Playful'],
        allowCustom: true,
      },
      {
        id: 'timbre.density',
        label: 'Density',
        options: ['Full', 'Homogenous', 'Light', 'Rich', 'Thin', 'Transparent'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'texture',
    color: '#a78bfa',
    label: 'Texture',
    fields: [
      {
        id: 'texture.element',
        label: 'Element name',
        options: ['Textural', 'Texture'],
        allowCustom: true,
      },
      {
        id: 'texture.type',
        label: 'Texture type',
        options: ['Contrapuntal', 'Homophonic', 'Monophonic', 'Polyphonic', 'Polyphony'],
        allowCustom: true,
      },
      {
        id: 'texture.role',
        label: 'Layer role',
        options: [
          'Accompaniment',
          'Bass line',
          'Counter-melody',
          'Melody',
          'Pad / drone',
          'Rhythmic',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.layers',
        label: 'Layer relationship & count',
        options: [
          'Block (chordal)',
          'Dialogue',
          'Doubled',
          'Doubling',
          'Independent',
          'Interplay',
          'Layered',
          'Layers',
          'Single line',
          'Unison (as texture)',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.density',
        label: 'Density',
        options: [
          'Busy',
          'Complex',
          'Dense',
          'Density',
          'Full',
          'Light',
          'Lighter',
          'Rich',
          'Sparse',
          'Thick',
          'Thicken',
          'Thin',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.devices',
        label: 'Compositional-device textures',
        options: [
          'Antiphonal',
          'Canon',
          'Canonic',
          'Countermelody',
          'Fugal',
          'Fugue-like',
          'Hocket',
          'Imitation',
          'Imitative',
          'Interlocking',
          'Staggered entries',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'structure',
    color: '#f97316',
    label: 'Structure',
    fields: [
      {
        id: 'structure.element',
        label: 'Element name',
        options: ['Form', 'Structural', 'Structure'],
        allowCustom: true,
      },
      {
        id: 'structure.phrase',
        label: 'Phrase & form shape',
        options: [
          'Arc-shaped',
          'Arch',
          'Cadenza',
          'Call-and-response',
          'Climactic',
          'Climax',
          'Coda',
          'Codetta',
          'Question-and-answer',
          'Sectional',
          'Sections',
          'Theme and variations',
          'Through-composed',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.repetition',
        label: 'Repetition & recurring material',
        options: [
          'Echo',
          'Echoed',
          'Mirrored',
          'Ostinato',
          'Recurring',
          'Repeated',
          'Repetition',
          'Thematic',
          'Thematic material',
          'Theme',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.development',
        label: 'Development of ideas',
        options: [
          'Augmented',
          'Developed',
          'Development',
          'Diminution',
          'Elaborated',
          'Extended',
          'Extension',
          'Fragmentation',
          'Fragmented',
          'Inversion',
          'Inverted',
          'Motif',
          'Motivic',
          'Sequence',
          'Sequential',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.imitation',
        label: 'Imitative / canonic devices',
        options: [
          'Antiphonal',
          'Canon',
          'Canonic',
          'Fugal',
          'Fugue-like',
          'Imitation',
          'Imitative',
          'Staggered',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.contrast',
        label: 'Contrast / variety',
        options: [
          'Alternating',
          'Contrasting',
          'Juxtaposed',
          'Variation',
          'Varied',
          'Variety',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.unity',
        label: 'Unity / cohesion',
        options: ['Consistent', 'Return', 'Returning', 'Unified', 'Unifying', 'Unity'],
        allowCustom: true,
      },
      {
        id: 'structure.balance',
        label: 'Balance & symmetry',
        options: ['Balance', 'Balanced', 'Even phrase length', 'Symmetrical'],
        allowCustom: true,
      },
    ],
  },
]

/**
 * Words that tag themselves as you type — the Auto-tag tick in Notion.
 * Only words nobody writes in their everyday sense belong here; "even",
 * "light" and "major" are deliberately absent.
 */
export const AUTO_TERMS: string[] = [
  'Accelerando',
  'Accented',
  'Accordion',
  'Acoustic guitar',
  'Aeolian',
  'Alla breve',
  'Allegro',
  'Alternating',
  'Alto flute',
  'Alto saxophone',
  'Anacrusis',
  'Animando',
  'Antiphonal',
  'Arc-shaped',
  'Arco',
  'Arpeggiated',
  'Articulation',
  'Ascending',
  'Augmentation',
  'Augmented',
  'Balance',
  'Banjo',
  'Baritone saxophone',
  'Bass clarinet',
  'Bass drum',
  'Bass guitar',
  'Bass trombone',
  'Basso continuo',
  'Bassoon',
  'Bell-like',
  'Bitonal',
  'Blowing',
  'Bongos',
  'Bowing',
  'Brass',
  'Cadential',
  'Cadenza',
  'Cajón',
  'Call-and-response',
  'Canon',
  'Canonic',
  'Cantabile',
  'Castanets',
  'Celesta',
  'Cello',
  'Chant-like',
  'Choir',
  'Chromatic',
  'Chromaticism',
  'Clarinet',
  'Claves',
  'Clavichord',
  'Climactic',
  'Cluster-like',
  'Clusters',
  'Coda',
  'Codetta',
  'Common time',
  'Compound',
  'Congas',
  'Conjunct',
  'Consonant',
  'Continuo',
  'Contrabassoon',
  'Contralto',
  'Contrapuntal',
  'Cor anglais',
  'Cornet',
  'Counter-melody',
  'Countermelody',
  'Countertenor',
  'Cowbell',
  'Crash cymbals',
  'Crescendo',
  'Cross-rhythm',
  'Cut common time',
  'Cymbals',
  'Dance-like',
  'Decrescendo',
  'Delicatamente',
  'Descending',
  'Diatonic',
  'Didgeridoo',
  'Diminished',
  'Diminuendo',
  'Diminution',
  'Disjunct',
  'Dissonance',
  'Dissonant',
  'Djembe',
  'Dolce',
  'Dorian',
  'Dotted',
  'Double bass',
  'Drone',
  'Drum kit',
  'Duet',
  'Duple',
  'Duplet',
  'Duration',
  'Dynamics',
  'Echoey',
  'Electric guitar',
  'Electric piano',
  'Erhu',
  'Espressivo',
  'Ethereal',
  'Euphonium',
  'Expressive techniques',
  'Falsetto',
  'Florid',
  'Flugelhorn',
  'Flute',
  'Fragmentation',
  'French horn',
  'Fugal',
  'Fugue-like',
  'Glissandi',
  'Glissando',
  'Glockenspiel',
  'Grazioso',
  'Guiro',
  'Guitar',
  'Harmonium',
  'Harp',
  'Harpsichord',
  'Hemiola',
  'Hemiolic',
  'Hi-hat',
  'Hocket',
  'Homogenous',
  'Homophonic',
  'Imitation',
  'Imitative',
  'Imperfect',
  'Instrumentation',
  'Inverted',
  'Koto',
  'Legato',
  'Leggierissimo',
  'Leggiero',
  'Lento',
  'Lilting',
  'Lyrical',
  'Maestoso',
  'Mandolin',
  'Maracas',
  'Marcato',
  'March-like',
  'Marimba',
  'Mellow',
  'Melodic',
  'Metallic',
  'Metre',
  'Mezzo-soprano',
  'Mixolydian',
  'Modal',
  'Modality',
  'Modulating',
  'Monophonic',
  'Motivic',
  'Multimetric',
  'Nasal',
  'Oboe',
  'Off-beat',
  'Orchestra',
  'Orchestration',
  'Ostinato',
  'Pan pipes',
  'Pentatonic',
  'Percussion',
  'Percussive',
  'Performing media',
  'Phrasing',
  'Phrygian',
  'Piccolo',
  'Pipe organ',
  'Pitch',
  'Pizzicato',
  'Plucking',
  'Polyphonic',
  'Polyphony',
  'Polyrhythm',
  'Polyrhythmic',
  'Polytonal',
  'Quadruple',
  'Quartal',
  'Quartet',
  'Question-and-answer',
  'Quintet',
  'Quintuplet',
  'Rallentando',
  'Rhythm',
  'Rhythmic',
  'Ritardando',
  'Ritenuto',
  'Rubato',
  'Saxophone',
  'Scale-based',
  'Scalic',
  'Sectional',
  'Semplice',
  'Sequential',
  'Sextuplet',
  'Sfzp',
  'Shakuhachi',
  'Sitar',
  'Slurred',
  'Slurs',
  'Snare drum',
  'Soprano',
  'Soprano saxophone',
  'Spiccato',
  'Sprechstimme',
  'Staccatissimo',
  'Staccato',
  'Staggered',
  'Stepwise',
  'Suspended cymbal',
  'Syncopated',
  'Synthesiser',
  'Taiko',
  'Tam-tam',
  'Tambourine',
  'Temple blocks',
  'Tempo',
  'Tenor saxophone',
  'Tenuto',
  'Terraced',
  'Tessitura',
  'Textural',
  'Texture',
  'Thematic',
  'Thematic material',
  'Through-composed',
  'Timbre',
  'Timpani',
  'Tonal',
  'Tone colour',
  'Tremolo',
  'Triadic',
  'Trill',
  'Trio',
  'Triple',
  'Triplet',
  'Trombone',
  'Trumpet',
  'Tuba',
  'Tubular bells',
  'Tutti',
  'Ukulele',
  'Unified',
  'Unresolved',
  'Vibraphone',
  'Vibrato',
  'Viola',
  'Violin',
  'Vocalise',
  'Warlike',
  'Whole-tone',
  'Woodblock',
  'Woodwind',
  'Xylophone',
]

/**
 * Alternative spellings prose is recognised by, mapped to the word they
 * stand for — the Aliases column. Irregular forms only: the regular
 * English ones are generated in propertyTags.ts and need no row here.
 */
export const ALIASES: Record<string, string> = {
  'arpeggio': 'Arpeggiated',
  'arpeggios': 'Arpeggiated',
  'cadence': 'Cadential',
  'cadences': 'Cadential',
  'cresc': 'Crescendo',
  'cresc.': 'Crescendo',
  'forte': 'f',
  'fortissimo': 'ff',
  'fortississimo': 'fff',
  'fugue': 'Fugue-like',
  'fugues': 'Fugue-like',
  'mezzo forte': 'mf',
  'mezzo piano': 'mp',
  'mezzo-forte': 'mf',
  'mezzo-piano': 'mp',
  'motifs': 'Motif',
  'motives': 'Motif',
  'pianissimo': 'pp',
  'pianississimo': 'ppp',
  'pizz': 'Pizzicato',
  'pizz.': 'Pizzicato',
  'rit.': 'Ritardando',
  'ritard.': 'Ritardando',
  'sequences': 'Sequence',
}

/**
 * What each word means and one line of it in use — the Definition column
 * and the Exemplar quote, keyed by `field:Term` because the same word in
 * two concepts is two different entries. Only words that have one or the
 * other appear here; the dictionary says so when a word has neither.
 */
export interface Gloss {
  /** Definition. */
  d: string
  /** Example of the word in use. */
  e: string
}
export const GLOSSARY: Record<string, Gloss> = {
  'duration.drive:Boisterous': { d: '', e: '“boisterous and energetic” (Trial 2021)' },
  'duration.drive:Busy': { d: '', e: '“create a busy soundscape” (HSC 2025); “more rhythmically busy accompaniment layers” (Trial 2009)' },
  'duration.drive:Driving': { d: '', e: '“Driving quaver pulse providing momentum” (HSC 2017)' },
  'duration.drive:Energetic': { d: '', e: '“boisterous and energetic” (Trial 2021)' },
  'duration.drive:Momentum': { d: '', e: '“momentum is maintained with ostinato like rhythm” (Trial 2021); “adds rhythmic momentum in a ‘moto perpetuo’ style” (Trial 2025)' },
  'duration.drive:Perpetual': { d: '', e: '“perpetual motion in the continuous rhythm” (Trial 2025)' },
  'duration.drive:Propelling': { d: '', e: '“the addition of a G propels the rhythm forward” (HSC 2024)' },
  'duration.drive:Relentless': { d: '', e: '“The accompanying semiquavers are relentless” (HSC 2023)' },
  'duration.drive:Rhythmic drive': { d: '', e: '“to give greater rhythmic drive” (HSC 2016); “Expressive devices enhance the rhythmic drive” (HSC 2025)' },
  'duration.feel:Chant-like': { d: '', e: '“voices — chant-like” (Trial 2008); “in a free chant-like rhythm” (Trial 2007)' },
  'duration.feel:Dance-like': { d: '', e: '“a lilting dance-like (rondo) motive” (Trial 2023); “This high spirited dance rhythm” (HSC 2018)' },
  'duration.feel:Lilting': { d: '', e: '“a lilting dance-like (rondo) motive” (Trial 2023)' },
  'duration.feel:March-like': { d: '', e: '“fast tempo — march-like or warlike” (Trial 2008)' },
  'duration.feel:Stamping': { d: '', e: '“‘stamping’ pattern in strings” (Trial 2008)' },
  'duration.feel:Warlike': { d: '', e: '“fast tempo — march-like or warlike” (Trial 2008)' },
  'duration.italian:Accelerando': { d: '', e: '“accelerando/ritardando” (HSC 2017); “a significant ritenuto in bar 32” (HSC 2025); “poco accel, animando and molto rall” (HSC 2022)' },
  'duration.italian:Allegretto grazioso': { d: '', e: '(Trial 2021, Trial 2025)' },
  'duration.italian:Allegro': { d: '', e: '(Trial 2021, Trial 2025)' },
  'duration.italian:Allegro Vivace': { d: '', e: '(Trial 2021, Trial 2025)' },
  'duration.italian:Animando': { d: '', e: '“accelerando/ritardando” (HSC 2017); “a significant ritenuto in bar 32” (HSC 2025); “poco accel, animando and molto rall” (HSC 2022)' },
  'duration.italian:Leggierissimo': { d: '', e: '(Trial 2021, Trial 2025)' },
  'duration.italian:Lento': { d: '', e: '“Maestoso (majestically)” (HSC 2022); “Lento maestoso — slowly and majestically” (Trial 2024)' },
  'duration.italian:Lento maestoso': { d: '', e: '“Maestoso (majestically)” (HSC 2022); “Lento maestoso — slowly and majestically” (Trial 2024)' },
  'duration.italian:Maestoso': { d: '', e: '“Maestoso (majestically)” (HSC 2022); “Lento maestoso — slowly and majestically” (Trial 2024)' },
  'duration.italian:Metric modulation': { d: '', e: '“Metric modulation keeps a commonality in tempo” (Trial 2024)' },
  'duration.italian:Moto perpetuo': { d: '', e: '“a ‘moto perpetuo’ style” (Trial 2025)' },
  'duration.italian:Rallentando': { d: '', e: '“accelerando/ritardando” (HSC 2017); “a significant ritenuto in bar 32” (HSC 2025); “poco accel, animando and molto rall” (HSC 2022)' },
  'duration.italian:Ritardando': { d: '', e: '“accelerando/ritardando” (HSC 2017); “a significant ritenuto in bar 32” (HSC 2025); “poco accel, animando and molto rall” (HSC 2022)' },
  'duration.italian:Ritenuto': { d: '', e: '“accelerando/ritardando” (HSC 2017); “a significant ritenuto in bar 32” (HSC 2025); “poco accel, animando and molto rall” (HSC 2022)' },
  'duration.italian:Rubato': { d: 'Expressive give and take in the tempo — time borrowed from one note and paid back in another.', e: '“use of heavy rubato” (HSC 2019); “Rhythmic ‘push and pull’ (rubato)” (HSC 2021)' },
  'duration.italian:Senza misura': { d: '', e: '“performed senza misura (without measure)” (HSC 2022)' },
  'duration.metre:Changing metre': { d: '', e: '“Rapid change in metre” (HSC 2020); “despite the changing metre” (HSC 2019)' },
  'duration.metre:Compound': { d: '', e: '“in compound duple time… crotchets and quavers” (Trial 2023)' },
  'duration.metre:Duple': { d: '', e: '“to further disguise the triple metre” (HSC 2023); “a strong duple 6/8 type rhythm” (HSC 2023); “Timpani ostinato gives strong quadruple metre” (Trial 2007)' },
  'duration.metre:Mixed metre': { d: '', e: '“use of mixed metre: 3/4 at the start to 4/4… then 2/4” (HSC 2017)' },
  'duration.metre:Multimetric': { d: '', e: '“Multimetric changes create variety” (HSC 2025); “many alterations of metre” (Trial 2019)' },
  'duration.metre:Quadruple': { d: '', e: '“to further disguise the triple metre” (HSC 2023); “a strong duple 6/8 type rhythm” (HSC 2023); “Timpani ostinato gives strong quadruple metre” (Trial 2007)' },
  'duration.metre:Simple triple': { d: '', e: '“shifting from simple triple to compound duple” (Trial 2024)' },
  'duration.metre:Triple': { d: '', e: '“to further disguise the triple metre” (HSC 2023); “a strong duple 6/8 type rhythm” (HSC 2023); “Timpani ostinato gives strong quadruple metre” (Trial 2007)' },
  'duration.steadiness:Balanced': { d: '', e: '“2-bar balanced syncopated ascending patterns” (Trial 2007)' },
  'duration.steadiness:Consistent': { d: '', e: '“establishes a consistent rhythm” (HSC 2019); “a consistent quadruple pulse feel” (Trial 2025)' },
  'duration.steadiness:Constant': { d: '', e: '“the constant semiquaver pattern” (HSC 2017); “Constant quaver pulse throughout” (HSC 2023)' },
  'duration.steadiness:Continuous': { d: '', e: '“continuous steady pulse” (Trial 2021); “Continuous semiquaver passages” (Trial 2025)' },
  'duration.steadiness:Even': { d: '', e: '“even harmonic rhythm” (HSC 2018)' },
  'duration.steadiness:Maintained': { d: '', e: '“a similar tempo is maintained throughout” (HSC 2019)' },
  'duration.steadiness:Pervasive': { d: '', e: '“The main quaver motif is pervasive” (Trial 2019)' },
  'duration.steadiness:Regular': { d: '', e: '“Changes in time signature that prevent a regular pulse” (HSC 2024); “the regular crotchet pulse” (Trial 2009)' },
  'duration.steadiness:Steady': { d: '', e: '“maintain a steady pulse” (HSC 2016); “steady, rapid pulse is established” (Trial 2007)' },
  'duration.syncopation:Ambiguous': { d: '', e: '“syncopation used to make the pulse ambiguous” (HSC 2022); “make the time signature ambiguous” (HSC 2023)' },
  'duration.syncopation:Cross-rhythm': { d: '', e: '“Cross-rhythms created in 2nd section” (HSC 2019); “a cross-rhythm between piano and strings” (HSC 2024)' },
  'duration.syncopation:Displaced': { d: '', e: '“the bass drum uses shifting accents” (HSC 2019); “rhythmically displaced by a quaver” (HSC 2023)' },
  'duration.syncopation:Hemiola': { d: 'Two bars of three beats heard as three bars of two, or the reverse — the pulse regroups without the time signature changing.', e: '“Hemiolic rhythmic grouping” (HSC 2018); “Makes use of a hemiola effect” (Trial 2021)' },
  'duration.syncopation:Hemiolic': { d: '', e: '“Hemiolic rhythmic grouping” (HSC 2018); “Makes use of a hemiola effect” (Trial 2021)' },
  'duration.syncopation:Off-beat': { d: '', e: '“syncopated off-beat semiquavers” (HSC 2019)' },
  'duration.syncopation:Polyrhythm': { d: '', e: '“detailed use of… polyrhythm” (HSC 2016); “Polyrhythmic ideas in continuous steady pulse” (Trial 2021)' },
  'duration.syncopation:Polyrhythmic': { d: '', e: '“detailed use of… polyrhythm” (HSC 2016); “Polyrhythmic ideas in continuous steady pulse” (Trial 2021)' },
  'duration.syncopation:Shifting': { d: '', e: '“the bass drum uses shifting accents” (HSC 2019); “rhythmically displaced by a quaver” (HSC 2023)' },
  'duration.syncopation:Syncopated': { d: 'Accents placed off the expected beat, so the stress falls where the pulse does not.', e: '“Heavy use of syncopation” (HSC 2020); “heavily syncopated and independent” (Trial 2007)' },
  'duration.syncopation:Uneven': { d: '', e: '“the uneven lengths of each bar” (HSC 2022)' },
  'duration.tempo:Fast': { d: '', e: '“begins at a very fast tempo” (HSC 2016); “Allegro Leggierissimo - fast and light as possible” (Trial 2025)' },
  'duration.tempo:Lively': { d: '', e: '“the tempo is 128 bpm which is a lively and quick tempo” (HSC 2025)' },
  'duration.tempo:Quick': { d: '', e: '“the notes alternate quickly” (HSC 2024); “a lively and quick tempo” (HSC 2025)' },
  'duration.tempo:Rapid': { d: '', e: '“Fragments of rapid-paced rhythm at first” (Trial 2007); “rapid notes” (Trial 2019)' },
  'duration.tempo:Slow': { d: '', e: '“commences in 4/4 time at a slow tempo” (HSC 2022); “A slow tempo but with movement” (Trial 2025)' },
  'duration.tempoChange:Acceleration': { d: '', e: '“a sense of acceleration by gradually introducing shorter note values” (HSC 2020); “rhythmic acceleration” (HSC 2024)' },
  'duration.tempoChange:Getting faster': { d: '', e: '“creating tension as they get faster” (HSC 2019)' },
  'duration.tempoChange:Slowing': { d: '', e: '“Music gradually slows down and quietens” (Trial 2008)' },
  'duration.values:Anacrusis': { d: 'One or more notes before the first strong beat — an upbeat leading into the bar.', e: '“Semi-quaver duplets give the effect of anacrusis patterns” (Trial 2007)' },
  'duration.values:Augmentation': { d: '', e: '“augmentation of four-note tuba motif” (HSC 2020); “Augmentation of rhythm in harp” (Trial 2009)' },
  'duration.values:Augmented': { d: '', e: '“augmentation of four-note tuba motif” (HSC 2020); “Augmentation of rhythm in harp” (Trial 2009)' },
  'duration.values:Diminution': { d: '', e: '“Diversity of rhythmic motifs and use of diminution” (HSC 2024)' },
  'duration.values:Dotted': { d: '', e: '“dotted rhythms at bar 213” (HSC 2018); “dotted quaver-semiquaver-pair quaver pattern” (HSC 2025)' },
  'duration.values:Duplet': { d: '', e: '“Semi-quaver duplets give the effect of anacrusis patterns” (Trial 2007)' },
  'duration.values:Long': { d: '', e: '“Longer held notes… at the ends of phrases” (HSC 2017); “Sustained long sounds (pedal point)” (HSC 2025)' },
  'duration.values:Quintuplet': { d: '', e: '“semiquavers that change to quintuplets” (HSC 2024)' },
  'duration.values:Sextuplet': { d: '', e: '“Introduction of sextuplet groupings” (HSC 2025)' },
  'duration.values:Short': { d: '', e: '“shorter note values” (HSC 2019); “Mostly short note values” (HSC 2023)' },
  'duration.values:Shorter': { d: '', e: '“shorter note values” (HSC 2019); “Mostly short note values” (HSC 2023)' },
  'duration.values:Snap': { d: '', e: '“the violin I and II, which play a ‘snap’ rhythm” (HSC 2022)' },
  'duration.values:Sustained': { d: '', e: '“Longer held notes… at the ends of phrases” (HSC 2017); “Sustained long sounds (pedal point)” (HSC 2025)' },
  'duration.values:Tied': { d: '', e: '“dotted quavers tied over the beat” (Trial 2021); “tied note durations like a pedal note” (Trial 2019)' },
  'duration.values:Triplet': { d: '', e: '“Rhythmic variety is created by using new triplets” (HSC 2018)' },
  'dynamics.change:Frequent': { d: '', e: '“frequent dynamic changes ranging from ppp to mp” (HSC 2024)' },
  'dynamics.change:Gradual': { d: '', e: '“gradually increasing to ff at bar 99” (HSC 2017)' },
  'dynamics.change:Gradually': { d: '', e: '“gradually increasing to ff at bar 99” (HSC 2017)' },
  'dynamics.change:Sudden': { d: '', e: '“Use of sudden dynamic changes” (HSC 2017)' },
  'dynamics.change:Swelling': { d: '', e: '“the dynamic swells suddenly”; “crescendo and decrescendo swells” (Trial 2021)' },
  'dynamics.change:Swells': { d: '', e: '“the dynamic swells suddenly”; “crescendo and decrescendo swells” (Trial 2021)' },
  'dynamics.change:Terraced': { d: '', e: '“a ‘terraced dynamic’ effect” (HSC 2025); “Dynamics are more terraced in the Allegro Vivace section” (Trial 2021)' },
  'dynamics.change:Varied': { d: '', e: '“the many varied dynamics” (HSC 2024)' },
  'dynamics.italian:Crescendo': { d: '', e: '“crescendos which build excitement” (HSC 2019); “Crescendo to decrescendo” (HSC 2020)' },
  'dynamics.italian:Decrescendo': { d: '', e: '“crescendos which build excitement” (HSC 2019); “Crescendo to decrescendo” (HSC 2020)' },
  'dynamics.italian:Diminuendo': { d: '', e: '“crescendos which build excitement” (HSC 2019); “Crescendo to decrescendo” (HSC 2020)' },
  'dynamics.italian:Dynamic letter levels (ppp–ff)': { d: '', e: '“from ppp (pianississimo – very, very soft) to p” (HSC 2024)' },
  'dynamics.italian:Fortepiano (fp)': { d: '', e: '“the use of sforzando by all instruments” (HSC 2018); “use of fp and sfzp” (HSC 2020)' },
  'dynamics.italian:Sforzando (sfz)': { d: '', e: '“the use of sforzando by all instruments” (HSC 2018); “use of fp and sfzp” (HSC 2020)' },
  'dynamics.italian:Sfzp': { d: '', e: '“the use of sforzando by all instruments” (HSC 2018); “use of fp and sfzp” (HSC 2020)' },
  'dynamics.loudness:Forced': { d: '', e: '“emphasising the high, forced C#” (HSC 2024)' },
  'dynamics.loudness:Limited': { d: '', e: '“Limited use of dynamic change” (HSC 2025)' },
  'dynamics.loudness:Loud': { d: '', e: '“Marimba 2 becomes louder” (HSC 2024); “fortissimo quavers from viola, cello and double bass” (HSC 2016)' },
  'dynamics.loudness:Quiet': { d: '', e: '“Mostly quiet dynamics” (Trial 2024)' },
  'dynamics.loudness:Soft': { d: '', e: '“louder in the middle of a phrase and softer again towards the end” (HSC 2022); “repeated softly (delicatamente)” (Trial 2023)' },
  'dynamics.loudness:Softer': { d: '', e: '“louder in the middle of a phrase and softer again towards the end” (HSC 2022); “repeated softly (delicatamente)” (Trial 2023)' },
  'dynamics.loudness:Static (volume)': { d: '', e: '“contrast with the static volume in other sections” (HSC 2019)' },
  'dynamics.loudness:Subtle': { d: '', e: '“the subtle shifts in dynamics” (Trial 2025)' },
  'dynamics.loudness:Wide (dynamic range)': { d: '', e: '“a wide dynamic range, from ppp to ff” (HSC 2022)' },
  'expressive.articulation:Accented': { d: '', e: '“Accented and staccato parts against legato lines” (HSC 2017)' },
  'expressive.articulation:Arco': { d: '', e: '“Double basses at bar 8 are pizzicato and at bar 11 are arco” (HSC 2025)' },
  'expressive.articulation:Detached': { d: '', e: '“very detached” (HSC 2025); “clearly articulated and detached” (Trial 2021)' },
  'expressive.articulation:Legato': { d: '', e: '“a languid, legato bowed melody” (HSC 2022)' },
  'expressive.articulation:Marcato': { d: '', e: '“marcato accents throughout the string section… adds a forceful tone colour” (HSC 2022)' },
  'expressive.articulation:Pizzicato': { d: '', e: '“Double basses at bar 8 are pizzicato and at bar 11 are arco” (HSC 2025)' },
  'expressive.articulation:Slurred': { d: '', e: '“Slurred phrasing in the left hand of the piano” (HSC 2024)' },
  'expressive.articulation:Slurs': { d: '', e: '“Slurred phrasing in the left hand of the piano” (HSC 2024)' },
  'expressive.articulation:Staccatissimo': { d: '', e: '“play always very detached” / “staccatissimo (very short)” (HSC 2025)' },
  'expressive.articulation:Staccato': { d: '', e: '“staccato and slurs/legato articulations” (HSC 2021)' },
  'expressive.articulation:Sustained': { d: '', e: '“low dynamic levels on sustained notes” (HSC 2018)' },
  'expressive.articulation:Tenuto': { d: '', e: '“tenuto phrasing in bar 8” (HSC 2019)' },
  'expressive.italian:‘Breathing’ marks': { d: '', e: '“performed sempre ad libitum” (HSC 2022); “senza misura (without measure)” (HSC 2022); “‘breathing’ indications” (HSC 2022)' },
  'expressive.italian:Ad libitum': { d: '', e: '“performed sempre ad libitum” (HSC 2022); “senza misura (without measure)” (HSC 2022); “‘breathing’ indications” (HSC 2022)' },
  'expressive.italian:Cantabile': { d: '', e: '“from dolce… to con forza” (HSC 2020); “marked espressivo” (Trial 2025); “lyrical and cantabile” (Trial 2021)' },
  'expressive.italian:Con forza': { d: '', e: '“from dolce… to con forza” (HSC 2020); “marked espressivo” (Trial 2025); “lyrical and cantabile” (Trial 2021)' },
  'expressive.italian:Con sordino (mute)': { d: '', e: '“senza sord… Without mute” (Trial 2024); “harmon mute” (HSC 2020)' },
  'expressive.italian:Delicatamente': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.italian:Dolce': { d: '', e: '“from dolce… to con forza” (HSC 2020); “marked espressivo” (Trial 2025); “lyrical and cantabile” (Trial 2021)' },
  'expressive.italian:Espressivo': { d: '', e: '“from dolce… to con forza” (HSC 2020); “marked espressivo” (Trial 2025); “lyrical and cantabile” (Trial 2021)' },
  'expressive.italian:Grazioso': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.italian:Leggierissimo': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.italian:Leggiero': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.italian:Semplice': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.italian:Senza misura': { d: '', e: '“performed sempre ad libitum” (HSC 2022); “senza misura (without measure)” (HSC 2022); “‘breathing’ indications” (HSC 2022)' },
  'expressive.italian:Senza sordino': { d: '', e: '“senza sord… Without mute” (Trial 2024); “harmon mute” (HSC 2020)' },
  'expressive.italian:Senza vibrato': { d: '', e: '“Strings senza vib — without vibrating” (Trial 2023)' },
  'expressive.italian:Sotto voce': { d: '', e: '“the leggiero style” (HSC 2023); “Allegretto grazioso” (Trial 2021); “marked sotto voce” (Trial 2021); “(delicatamente)” (Trial 2023); “semplice… play simply” (Trial 2009)' },
  'expressive.phrasing:Animated (animando)': { d: '', e: '“perform in an animated manner” (HSC 2022)' },
  'expressive.phrasing:Barbaric (feroce)': { d: '', e: '“‘intenso, barbaro’ (intense, savage)… ‘feroce’” (Trial 2023)' },
  'expressive.phrasing:Boisterous': { d: '', e: '“boisterous and energetic” (Trial 2021)' },
  'expressive.phrasing:Delicate': { d: '', e: '“the delicate and ‘playful’ scherzo feel” (Trial 2025)' },
  'expressive.phrasing:Dramatic': { d: '', e: '“Dramatic changes in dynamics from pianissimo to sforzando” (HSC 2023)' },
  'expressive.phrasing:Energetic': { d: '', e: '“boisterous and energetic” (Trial 2021)' },
  'expressive.phrasing:Expressive': { d: '', e: '“Expressive, legato upper woodwinds” (HSC 2022)' },
  'expressive.phrasing:Forceful': { d: '', e: '“the forceful pizz. from the cello and double bass” (HSC 2020)' },
  'expressive.phrasing:Graceful': { d: '', e: '“the overall mood is graceful and sweet — dolce” (Trial 2021)' },
  'expressive.phrasing:Intense': { d: '', e: '“Use of intense dynamic changes” (HSC 2024)' },
  'expressive.phrasing:Languid': { d: '', e: '“a languid, legato bowed melody” (HSC 2022)' },
  'expressive.phrasing:Lyrical': { d: '', e: '“more lyrical and expressive” (Trial 2021)' },
  'expressive.phrasing:Majestic (maestoso)': { d: '', e: '“slowly and majestically” (Trial 2024); “Maestoso (majestically)” (HSC 2022)' },
  'expressive.phrasing:Playful': { d: '', e: '“the delicate and ‘playful’ scherzo feel” (Trial 2025)' },
  'expressive.phrasing:Relentless': { d: '', e: '“The accompanying semiquavers are relentless” (HSC 2023)' },
  'expressive.phrasing:Savage': { d: '', e: '“‘intenso, barbaro’ (intense, savage)… ‘feroce’” (Trial 2023)' },
  'expressive.phrasing:Sweet (dolce)': { d: '', e: '“the overall mood is graceful and sweet — dolce” (Trial 2021)' },
  'expressive.phrasing:Urgent': { d: '', e: '“a sense of urgency” (Trial 2021)' },
  'expressive.technique:Bartók pizz.': { d: '', e: '“snap pizzicato (bar 24)” (HSC 2024); “Bartok pizz.” (HSC 2020)' },
  'expressive.technique:Col legno': { d: '', e: '“sul ponticello gives the string tone a harsh, almost metallic edge” (Trial 2009); “sul tasto for a very ethereal sound” (Trial 2023); “Col legno — percussive wooden sound” (Trial 2009)' },
  'expressive.technique:Glissandi': { d: '', e: '“The Harp plays a glissando” (HSC 2025)' },
  'expressive.technique:Glissando': { d: 'A continuous slide between two pitches, sounding everything that lies between them.', e: '“The Harp plays a glissando” (HSC 2025)' },
  'expressive.technique:Jeté bowing': { d: '', e: '“Jeté bowing – bouncing the bow on the strings to create a light tone colour” (HSC 2024)' },
  'expressive.technique:Laissez vibrer': { d: '', e: '“Let the sound ring and decay without stopping” (HSC 2024)' },
  'expressive.technique:Slap tonguing': { d: '', e: '“slap tonguing (bar 12)” (HSC 2019)' },
  'expressive.technique:Snap pizzicato': { d: '', e: '“snap pizzicato (bar 24)” (HSC 2024); “Bartok pizz.” (HSC 2020)' },
  'expressive.technique:Spiccato': { d: '', e: '“light spiccato bowing” (Trial 2025)' },
  'expressive.technique:Sul ponticello': { d: '', e: '“sul ponticello gives the string tone a harsh, almost metallic edge” (Trial 2009); “sul tasto for a very ethereal sound” (Trial 2023); “Col legno — percussive wooden sound” (Trial 2009)' },
  'expressive.technique:Sul tasto': { d: '', e: '“sul ponticello gives the string tone a harsh, almost metallic edge” (Trial 2009); “sul tasto for a very ethereal sound” (Trial 2023); “Col legno — percussive wooden sound” (Trial 2009)' },
  'expressive.technique:Tremolo': { d: 'Rapid repetition of a note, or fast alternation between two — heard as a shimmer or a tremble.', e: '“The tremolo of the strings… enhances the full textures” (HSC 2021); “Gentle tremolo vibraphone” (Trial 2023)' },
  'expressive.technique:Trill': { d: '', e: '“a trill notated in bar 2… adding expressive interest” (HSC 2021)' },
  'expressive.technique:Vibrato': { d: '', e: '“expressive vibrato and legato bowing” (Trial 2021); “Use of vibrato with varying speeds” (Trial 2007)' },
  'media.woodwind:Cor anglais': { d: 'The alto of the oboe family, pitched in F a fifth below the oboe — darker and more plaintive in tone.', e: '' },
  'pitch.cadence:Cadential': { d: '', e: '“with a perfect cadence” (Trial 2023); “Use of imperfect cadence… unresolved” (HSC 2016); “an extended cadential section” (HSC 2018)' },
  'pitch.cadence:Imperfect': { d: '', e: '“with a perfect cadence” (Trial 2023); “Use of imperfect cadence… unresolved” (HSC 2016); “an extended cadential section” (HSC 2018)' },
  'pitch.cadence:Perfect': { d: '', e: '“with a perfect cadence” (Trial 2023); “Use of imperfect cadence… unresolved” (HSC 2016); “an extended cadential section” (HSC 2018)' },
  'pitch.consonance:Cluster-like': { d: '', e: '“Tone clusters” (HSC 2016); “Very low cluster-like chords” (Trial 2023)' },
  'pitch.consonance:Clusters': { d: '', e: '“Tone clusters” (HSC 2016); “Very low cluster-like chords” (Trial 2023)' },
  'pitch.consonance:Consonant': { d: '', e: '“resolving to consonant chords” (HSC 2021)' },
  'pitch.consonance:Dissonance': { d: '', e: '“much use of dissonance… to create tension” (HSC 2016); “Predominance of slightly dissonant chords” (Trial 2024)' },
  'pitch.consonance:Dissonant': { d: '', e: '“much use of dissonance… to create tension” (HSC 2016); “Predominance of slightly dissonant chords” (Trial 2024)' },
  'pitch.consonance:Semitone dissonance': { d: '', e: '“creates semitone dissonances against the tonic pedal point” (Trial 2007)' },
  'pitch.contour:Angular': { d: '', e: '“the complex rhythms and angular pitch material” (HSC 2024)' },
  'pitch.contour:Arc-shaped': { d: '', e: '“The first phrase is arc shaped” (Trial 2008)' },
  'pitch.contour:Ascending': { d: '', e: '“an ascending tonic chord outline” (HSC 2021); “a descending melodic minor scale” (HSC 2021)' },
  'pitch.contour:Conjunct': { d: '', e: '“a stepwise melody over a wide range” (HSC 2019); “mostly conjunct, moving in small steps/skips” (HSC 2024)' },
  'pitch.contour:Contour': { d: '', e: '“The pitch contour… contrasts widely” (HSC 2025); “changing contours, registers and dynamic levels” (Trial 2023)' },
  'pitch.contour:Contrary motion': { d: '', e: '“Contrary motion used between lower and upper strings” (HSC 2020); “Similar motion melodic movement” (HSC 2021); “a parallel third harmony” (Trial 2007)' },
  'pitch.contour:Descending': { d: '', e: '“an ascending tonic chord outline” (HSC 2021); “a descending melodic minor scale” (HSC 2021)' },
  'pitch.contour:Disjunct': { d: '', e: '“stepwise movement and small leaps… and larger leaps” (HSC 2021)' },
  'pitch.contour:Florid': { d: '', e: '“bassoon florid passage” (HSC 2025)' },
  'pitch.contour:Leap': { d: '', e: '“stepwise movement and small leaps… and larger leaps” (HSC 2021)' },
  'pitch.contour:Parallel motion': { d: '', e: '“Contrary motion used between lower and upper strings” (HSC 2020); “Similar motion melodic movement” (HSC 2021); “a parallel third harmony” (Trial 2007)' },
  'pitch.contour:Sequence': { d: '', e: '“Use of sequence descending stepwise” (HSC 2020); “developed into a sequential pattern” (Trial 2021)' },
  'pitch.contour:Sequential': { d: '', e: '“Use of sequence descending stepwise” (HSC 2020); “developed into a sequential pattern” (Trial 2021)' },
  'pitch.contour:Similar motion': { d: '', e: '“Contrary motion used between lower and upper strings” (HSC 2020); “Similar motion melodic movement” (HSC 2021); “a parallel third harmony” (Trial 2007)' },
  'pitch.contour:Smooth': { d: '', e: '“Melodies explore a wide range with smooth contour” (HSC 2020)' },
  'pitch.contour:Static': { d: '', e: '“the piano features a static melody” (HSC 2019); “the more static movement of the accompanying orchestra” (HSC 2025)' },
  'pitch.contour:Stepwise': { d: '', e: '“a stepwise melody over a wide range” (HSC 2019); “mostly conjunct, moving in small steps/skips” (HSC 2024)' },
  'pitch.contour:Virtuosic': { d: '', e: '“the virtuosic triplet figure bassoon writing” (HSC 2025)' },
  'pitch.harmony:Arpeggiated': { d: '', e: '“flowing arpeggio accompaniment” (HSC 2020); “broken chord arpeggio-style runs” (HSC 2025)' },
  'pitch.harmony:Augmented': { d: '', e: '“a descending D# diminished chord outline” (HSC 2021); “parallel augmented triads” (Trial 2025)' },
  'pitch.harmony:Block chords': { d: '', e: '“Block chords in trumpets… creating dissonance” (HSC 2020)' },
  'pitch.harmony:Broken chords': { d: '', e: '“flowing arpeggio accompaniment” (HSC 2020); “broken chord arpeggio-style runs” (HSC 2025)' },
  'pitch.harmony:Diminished': { d: '', e: '“a descending D# diminished chord outline” (HSC 2021); “parallel augmented triads” (Trial 2025)' },
  'pitch.harmony:Drone': { d: '', e: '“Low bass drone/pedal layer” (HSC 2019); “Upper pedal point” (HSC 2016)' },
  'pitch.harmony:Inverted': { d: '', e: '“all root position chords” (HSC 2017); “A Major in first inversion” (HSC 2023)' },
  'pitch.harmony:Major 7': { d: '', e: '“Features major 7 chords” (Trial 2021); “combinations of open 5ths” (HSC 2020)' },
  'pitch.harmony:Open 5ths': { d: '', e: '“Features major 7 chords” (Trial 2021); “combinations of open 5ths” (HSC 2020)' },
  'pitch.harmony:Pedal point': { d: 'A sustained or repeated note, usually in the bass, held while the harmony above it changes.', e: '“Low bass drone/pedal layer” (HSC 2019); “Upper pedal point” (HSC 2016)' },
  'pitch.harmony:Quartal': { d: '', e: '“Use of quartal harmonies” (HSC 2018)' },
  'pitch.harmony:Resolution': { d: '', e: '“suspension and resolution in the harmony” (HSC 2021)' },
  'pitch.harmony:Resolved': { d: '', e: '“suspension and resolution in the harmony” (HSC 2021)' },
  'pitch.harmony:Root position': { d: '', e: '“all root position chords” (HSC 2017); “A Major in first inversion” (HSC 2023)' },
  'pitch.harmony:Suspended': { d: '', e: '“The use of suspension… establishes tension” (HSC 2021); “triple suspensions” (Trial 2019)' },
  'pitch.harmony:Suspension': { d: '', e: '“The use of suspension… establishes tension” (HSC 2021); “triple suspensions” (Trial 2019)' },
  'pitch.harmony:Tonic-and-dominant based': { d: '', e: '“Harmonic vocabulary is very tonic and dominant based” (Trial 2019)' },
  'pitch.harmony:Triadic': { d: '', e: '“the melody… is triadic” (Trial 2023); “triadic harmony” (Trial 2021)' },
  'pitch.harmony:Unresolved': { d: '', e: '“imperfect cadence… unresolved” (HSC 2016); “an unsettled, unresolved harmony” (HSC 2021)' },
  'pitch.range:High register': { d: '', e: '“at a higher register” (HSC 2020); “high register (Soprano 1)” (HSC 2024)' },
  'pitch.range:Limited range': { d: '', e: '“Narrow range of pitch, and the register” (HSC 2019); “Relatively narrow range of melody” (HSC 2024)' },
  'pitch.range:Low register': { d: '', e: '“in a low register which creates a sense of foreboding” (HSC 2023)' },
  'pitch.range:Narrow range': { d: '', e: '“Narrow range of pitch, and the register” (HSC 2019); “Relatively narrow range of melody” (HSC 2024)' },
  'pitch.range:Register extremes': { d: '', e: '“the exploration of register” (HSC 2017); “Extreme registers on piano are explored” (HSC 2024)' },
  'pitch.range:Tessitura': { d: 'The part of the range a line mostly sits in, as distinct from the extremes it occasionally touches.', e: '“contrasts in the register/tessitura of performing media” (HSC 2021)' },
  'pitch.range:Wide range': { d: '', e: '“a wider pitch range” (HSC 2016); “piano spanning 4-5 octaves” (Trial 2021)' },
  'pitch.scale:Aeolian': { d: '', e: '“C mixolydian scale” (HSC 2022); “an E Dorian mode” (HSC 2019); “F# Aeolian mode” (HSC 2019); “a sense of Phrygian mode” (Trial 2024)' },
  'pitch.scale:Chromatic scale': { d: '', e: '“ascending and descending chromatic scale” (Trial 2025)' },
  'pitch.scale:Dorian': { d: '', e: '“C mixolydian scale” (HSC 2022); “an E Dorian mode” (HSC 2019); “F# Aeolian mode” (HSC 2019); “a sense of Phrygian mode” (Trial 2024)' },
  'pitch.scale:Harmonic minor': { d: '', e: '“the tonic minor (harmonic)” (Trial 2007)' },
  'pitch.scale:Mixolydian': { d: '', e: '“C mixolydian scale” (HSC 2022); “an E Dorian mode” (HSC 2019); “F# Aeolian mode” (HSC 2019); “a sense of Phrygian mode” (Trial 2024)' },
  'pitch.scale:Pentatonic': { d: 'A five-note scale, most often with no semitones — the black keys of a piano are one.', e: '“based on pentatonic scale” (Trial 2024)' },
  'pitch.scale:Phrygian': { d: '', e: '“C mixolydian scale” (HSC 2022); “an E Dorian mode” (HSC 2019); “F# Aeolian mode” (HSC 2019); “a sense of Phrygian mode” (Trial 2024)' },
  'pitch.scale:Scale-based': { d: '', e: '“A repeated scalic clarinet motif” (HSC 2016); “scale-based melodies” (HSC 2019)' },
  'pitch.scale:Scalic': { d: '', e: '“A repeated scalic clarinet motif” (HSC 2016); “scale-based melodies” (HSC 2019)' },
  'pitch.scale:Whole-tone': { d: '', e: '“subito whole-tone trills” (HSC 2018); “a descending whole tone semiquaver passage” (Trial 2024)' },
  'pitch.tonality:Bitonal': { d: '', e: '“creates bitonality” (Trial 2024); “modulates to… a polytonal key” (Trial 2007)' },
  'pitch.tonality:Chromatic': { d: '', e: '“features chromatic movement” (HSC 2021); “Violin semiquaver chromatic figures” (HSC 2023)' },
  'pitch.tonality:Chromaticism': { d: 'Use of notes from outside the prevailing key, typically moving by semitone.', e: '“Use of dissonance and chromaticism” (HSC 2017)' },
  'pitch.tonality:Diatonic': { d: '', e: '“mostly diatonic chords” (HSC 2025); “diatonic chord progressions” (Trial 2021)' },
  'pitch.tonality:Major': { d: '', e: '“to the final chord… a G major chord” (HSC 2022); “ends in the tonic major (‘tierce de picardie’)” (Trial 2019)' },
  'pitch.tonality:Minor': { d: '', e: '“reinforcing minor tonality” (HSC 2016); “a strong sense of minor tonality” (Trial 2019)' },
  'pitch.tonality:Modal': { d: '', e: '“in a modal tonality” (HSC 2022); “Modality versus major/minor tonality” (Trial 2024)' },
  'pitch.tonality:Modality': { d: '', e: '“in a modal tonality” (HSC 2022); “Modality versus major/minor tonality” (Trial 2024)' },
  'pitch.tonality:Modulating': { d: '', e: '“modulates through a number of keys” (HSC 2018)' },
  'pitch.tonality:Picardy 3rd': { d: '', e: '“use of a Picardy 3rd” (HSC 2022); “(‘tierce de picardie’)” (Trial 2019)' },
  'pitch.tonality:Polytonal': { d: '', e: '“creates bitonality” (Trial 2024); “modulates to… a polytonal key” (Trial 2007)' },
  'pitch.tonality:Tierce de picardie': { d: '', e: '“use of a Picardy 3rd” (HSC 2022); “(‘tierce de picardie’)” (Trial 2019)' },
  'pitch.tonality:Tonal': { d: '', e: '“creates an E tonal centre/pedal point” (HSC 2020); “a strong tonal centre on C” (Trial 2009)' },
  'pitch.tonality:Tonal ambiguity': { d: '', e: '“create a certain tonal ambiguity” (Trial 2024)' },
  'pitch.tonality:Tonal centre': { d: '', e: '“creates an E tonal centre/pedal point” (HSC 2020); “a strong tonal centre on C” (Trial 2009)' },
  'structure.balance:Balance': { d: '', e: '“three four-bar phrases, providing balance” (HSC 2018); “Balanced phrases were a feature of the Classical period” (HSC 2025)' },
  'structure.balance:Balanced': { d: '', e: '“three four-bar phrases, providing balance” (HSC 2018); “Balanced phrases were a feature of the Classical period” (HSC 2025)' },
  'structure.balance:Even phrase length': { d: '', e: '“The first 2 phrases are even in length, while the third is significantly longer” (Trial 2008)' },
  'structure.balance:Symmetrical': { d: '', e: '“Two halves roughly the same length which gives structural symmetry” (Trial 2024)' },
  'structure.contrast:Alternating': { d: '', e: '“alternates between block chords and a monophonic texture” (HSC 2021)' },
  'structure.contrast:Contrasting': { d: '', e: '“contrasted with the string chordal writing” (HSC 2016)' },
  'structure.contrast:Juxtaposed': { d: '', e: '“woodwind/strings/percussion juxtaposed” (HSC 2016); “Juxtaposition… of the whole tone scale and pentatonic scale” (Trial 2024)' },
  'structure.contrast:Variation': { d: '', e: '“Variety is achieved through the composer manipulating different concepts” (HSC 2018)' },
  'structure.contrast:Varied': { d: '', e: '“Variety is achieved through the composer manipulating different concepts” (HSC 2018)' },
  'structure.contrast:Variety': { d: '', e: '“Variety is achieved through the composer manipulating different concepts” (HSC 2018)' },
  'structure.development:Augmented': { d: '', e: '“augmentation of four-note tuba motif” (HSC 2020); “Augmentation and Diminution” (Trial 2021)' },
  'structure.development:Developed': { d: '', e: '“The theme is fragmented and developed” (HSC 2017); “developed into a sequential pattern” (Trial 2021)' },
  'structure.development:Development': { d: '', e: '“The theme is fragmented and developed” (HSC 2017); “developed into a sequential pattern” (Trial 2021)' },
  'structure.development:Diminution': { d: '', e: '“augmentation of four-note tuba motif” (HSC 2020); “Augmentation and Diminution” (Trial 2021)' },
  'structure.development:Elaborated': { d: '', e: '“Melodic line elaborated with the addition of repeated notes” (HSC 2016)' },
  'structure.development:Extended': { d: '', e: '“Theme is repeated and extended” (HSC 2017); “Motivic extension” (Trial 2021)' },
  'structure.development:Extension': { d: '', e: '“Theme is repeated and extended” (HSC 2017); “Motivic extension” (Trial 2021)' },
  'structure.development:Fragmentation': { d: '', e: '“Question/answer fragmentation of melody” (HSC 2016)' },
  'structure.development:Fragmented': { d: '', e: '“Question/answer fragmentation of melody” (HSC 2016)' },
  'structure.development:Inversion': { d: '', e: '“Melodic Inversion” (HSC 2016); “Inversion (bass bar 61)” (Trial 2021)' },
  'structure.development:Inverted': { d: '', e: '“Melodic Inversion” (HSC 2016); “Inversion (bass bar 61)” (Trial 2021)' },
  'structure.development:Motif': { d: '', e: '“Repetition of short fragments of motivic material” (Trial 2025)' },
  'structure.development:Motivic': { d: '', e: '“Repetition of short fragments of motivic material” (Trial 2025)' },
  'structure.development:Sequence': { d: '', e: '“Sequential on-the-beat solo line writing” (HSC 2025)' },
  'structure.development:Sequential': { d: '', e: '“Sequential on-the-beat solo line writing” (HSC 2025)' },
  'structure.imitation:Antiphonal': { d: '', e: '“Spacing of antiphonal entries varies” (Trial 2024)' },
  'structure.imitation:Canon': { d: '', e: '“the canonic entries of the choir parts” (HSC 2017); “a 6-part canon” (Trial 2025)' },
  'structure.imitation:Canonic': { d: '', e: '“the canonic entries of the choir parts” (HSC 2017); “a 6-part canon” (Trial 2025)' },
  'structure.imitation:Fugal': { d: '', e: '“a fugal episode based on theme 1” (HSC 2018)' },
  'structure.imitation:Fugue-like': { d: '', e: '“a fugal episode based on theme 1” (HSC 2018)' },
  'structure.imitation:Imitation': { d: '', e: '“Imitation of melodic material” (HSC 2017); “Imitation between parts throughout” (Trial 2025)' },
  'structure.imitation:Imitative': { d: '', e: '“Imitation of melodic material” (HSC 2017); “Imitation between parts throughout” (Trial 2025)' },
  'structure.imitation:Staggered': { d: '', e: '“staggered entries that imitate different bells” (HSC 2017)' },
  'structure.phrase:Arc-shaped': { d: '', e: '“a unifying arch structure” (HSC 2016); “The first phrase is arc shaped” (Trial 2008)' },
  'structure.phrase:Arch': { d: '', e: '“a unifying arch structure” (HSC 2016); “The first phrase is arc shaped” (Trial 2008)' },
  'structure.phrase:Cadenza': { d: '', e: '“extends it into a cadenza” (HSC 2021); “leading to the codetta” (Trial 2024); “In the Coda” (HSC 2025)' },
  'structure.phrase:Call-and-response': { d: '', e: '“Question and answers section between strings and brass/wind” (HSC 2018); “Use of rests in call and response passages” (Trial 2025)' },
  'structure.phrase:Climactic': { d: '', e: '“used to build to a climax” (HSC 2018); “the textural density of this climactic section” (HSC 2025)' },
  'structure.phrase:Climax': { d: '', e: '“used to build to a climax” (HSC 2018); “the textural density of this climactic section” (HSC 2025)' },
  'structure.phrase:Coda': { d: '', e: '“extends it into a cadenza” (HSC 2021); “leading to the codetta” (Trial 2024); “In the Coda” (HSC 2025)' },
  'structure.phrase:Codetta': { d: '', e: '“extends it into a cadenza” (HSC 2021); “leading to the codetta” (Trial 2024); “In the Coda” (HSC 2025)' },
  'structure.phrase:Question-and-answer': { d: '', e: '“Question and answers section between strings and brass/wind” (HSC 2018); “Use of rests in call and response passages” (Trial 2025)' },
  'structure.phrase:Sectional': { d: '', e: '“Three main sections” (HSC 2018)' },
  'structure.phrase:Sections': { d: '', e: '“Three main sections” (HSC 2018)' },
  'structure.phrase:Theme and variations': { d: '', e: '“Theme and variations” (HSC 2018)' },
  'structure.phrase:Through-composed': { d: 'Music that keeps moving to new material rather than returning to earlier sections.', e: '“the excerpt is through composed creating interest” (Trial 2023)' },
  'structure.repetition:Echoed': { d: '', e: '“are echoed by flutes and 1st clarinet” (HSC 2020); “mirrored by woodwinds” (HSC 2018)' },
  'structure.repetition:Mirrored': { d: '', e: '“are echoed by flutes and 1st clarinet” (HSC 2020); “mirrored by woodwinds” (HSC 2018)' },
  'structure.repetition:Ostinato': { d: 'A short pattern repeated persistently at the same pitch, usually underneath other material.', e: '“the ostinato first heard in the strings is heard again” (HSC 2019)' },
  'structure.repetition:Recurring': { d: '', e: '“It then is used as a recurring motif” (HSC 2024)' },
  'structure.repetition:Repeated': { d: '', e: '“Repetition of phrases in Sections B and C” (HSC 2018)' },
  'structure.repetition:Repetition': { d: '', e: '“Repetition of phrases in Sections B and C” (HSC 2018)' },
  'structure.unity:Consistent': { d: '', e: '“Consistent phrasing and rhythm patterns create balance” (HSC 2018)' },
  'structure.unity:Return': { d: '', e: '“Brief return of the opening sax solo melody… creates a sense of unity” (Trial 2025)' },
  'structure.unity:Returning': { d: '', e: '“Brief return of the opening sax solo melody… creates a sense of unity” (Trial 2025)' },
  'structure.unity:Unified': { d: '', e: '“a unifying arch structure” (HSC 2016); “Unity is achieved through the constant semiquaver pattern” (HSC 2017); “Unity is achieved by the use of repeated motifs” (Trial 2021)' },
  'structure.unity:Unifying': { d: '', e: '“a unifying arch structure” (HSC 2016); “Unity is achieved through the constant semiquaver pattern” (HSC 2017); “Unity is achieved by the use of repeated motifs” (Trial 2021)' },
  'structure.unity:Unity': { d: '', e: '“a unifying arch structure” (HSC 2016); “Unity is achieved through the constant semiquaver pattern” (HSC 2017); “Unity is achieved by the use of repeated motifs” (Trial 2021)' },
  'texture.density:Busy': { d: '', e: '“the very busy nature of the musical ideas” (HSC 2016)' },
  'texture.density:Complex': { d: '', e: '“a dense, complex homophonic texture” (HSC 2016); “The increasing complexity of the texture” (HSC 2018)' },
  'texture.density:Dense': { d: '', e: '“increases in density” (HSC 2016); “a more dense texture” (HSC 2019); “The texture is quite dense due to parts with rapid notes” (Trial 2021)' },
  'texture.density:Density': { d: '', e: '“increases in density” (HSC 2016); “a more dense texture” (HSC 2019); “The texture is quite dense due to parts with rapid notes” (Trial 2021)' },
  'texture.density:Full': { d: '', e: '“rich full texture when all instruments are playing” (HSC 2018); “The texture is full and rich” (HSC 2022)' },
  'texture.density:Light': { d: '', e: '“Texture is lighter at bars 178–182” (HSC 2018); “Light, transparent textures” (Trial 2024)' },
  'texture.density:Lighter': { d: '', e: '“Texture is lighter at bars 178–182” (HSC 2018); “Light, transparent textures” (Trial 2024)' },
  'texture.density:Rich': { d: '', e: '“rich full texture when all instruments are playing” (HSC 2018); “The texture is full and rich” (HSC 2022)' },
  'texture.density:Sparse': { d: '', e: '“The sparse texture at bar 177” (HSC 2020); “a sparse ‘light’ texture” (HSC 2023); “A light and sparse texture” (Trial 2025)' },
  'texture.density:Thick': { d: '', e: '“creates a thicker texture” (HSC 2016); “Gradual thickening of texture adds to tension” (HSC 2021); “piano thick chords” (Trial 2021)' },
  'texture.density:Thicken': { d: '', e: '“creates a thicker texture” (HSC 2016); “Gradual thickening of texture adds to tension” (HSC 2021); “piano thick chords” (Trial 2021)' },
  'texture.density:Thin': { d: '', e: '“the texture then becomes thin” (HSC 2018); “tacets into a thinner texture” (Trial 2021)' },
  'texture.devices:Antiphonal': { d: '', e: '“more polyphonic or antiphonal in the second” (Trial 2019); “Spacing of antiphonal entries varies” (Trial 2024)' },
  'texture.devices:Canon': { d: '', e: '“Canonic/staggered entries” (HSC 2016); “The excerpt is a 6-part canon” (Trial 2025)' },
  'texture.devices:Canonic': { d: '', e: '“Canonic/staggered entries” (HSC 2016); “The excerpt is a 6-part canon” (Trial 2025)' },
  'texture.devices:Countermelody': { d: '', e: '“an additional countermelody… creating a polyphonic texture” (HSC 2021)' },
  'texture.devices:Fugal': { d: '', e: '“played in fugal style” (HSC 2018); “a fugue-like opening” (HSC 2017)' },
  'texture.devices:Fugue-like': { d: '', e: '“played in fugal style” (HSC 2018); “a fugue-like opening” (HSC 2017)' },
  'texture.devices:Hocket': { d: '', e: '“Use of hocket features and interlocking rhythms” (Trial 2021)' },
  'texture.devices:Imitation': { d: '', e: '“textural interplay… creating contrast” (HSC 2023)' },
  'texture.devices:Imitative': { d: '', e: '“textural interplay… creating contrast” (HSC 2023)' },
  'texture.devices:Interlocking': { d: '', e: '“Use of hocket features and interlocking rhythms” (Trial 2021)' },
  'texture.devices:Staggered entries': { d: '', e: '“staggered oboe, flute, clarinet and bassoon entries” (HSC 2018); “Staggered entries increase textural density” (HSC 2024)' },
  'texture.element:Texture': { d: 'How many layers of sound there are and how they relate — one line, a melody with accompaniment, or several independent parts.', e: '' },
  'texture.layers:Block (chordal)': { d: '', e: '“all parts singing block rhythms/harmonies” (HSC 2016); “moves in block chords” (HSC 2022)' },
  'texture.layers:Dialogue': { d: '', e: '“Interplay between instruments is created” (HSC 2018); “dialogue between the parts” (HSC 2023)' },
  'texture.layers:Doubled': { d: '', e: '“violin 2 doubling down an octave” (HSC 2024); “Doubling contributes to density” (Trial 2025)' },
  'texture.layers:Doubling': { d: '', e: '“violin 2 doubling down an octave” (HSC 2024); “Doubling contributes to density” (Trial 2025)' },
  'texture.layers:Independent': { d: '', e: '“the cello has an independent bass line” (HSC 2023); “independent voice movement” (HSC 2025)' },
  'texture.layers:Interplay': { d: '', e: '“Interplay between instruments is created” (HSC 2018); “dialogue between the parts” (HSC 2023)' },
  'texture.layers:Layered': { d: '', e: '“A second and third layer are added” (HSC 2019); “three different rhythmic layers” (HSC 2022); “Multilayered score” (Trial 2023)' },
  'texture.layers:Layers': { d: '', e: '“A second and third layer are added” (HSC 2019); “three different rhythmic layers” (HSC 2022); “Multilayered score” (Trial 2023)' },
  'texture.layers:Single line': { d: '', e: '“the single melodic line at the beginning” (HSC 2019)' },
  'texture.layers:Unison (as texture)': { d: '', e: '“Tenor and Bass voices… singing in unison” (HSC 2022); “all instruments in unison” (Trial 2019)' },
  'texture.type:Contrapuntal': { d: '', e: '“demonstrates contrapuntal elaboration between layers” (HSC 2018)' },
  'texture.type:Homophonic': { d: 'One melody supported by chords, the parts moving in broadly the same rhythm.', e: '“creating a dense, complex homophonic texture” (HSC 2016); “a thin, homophonic texture” (HSC 2019); “note-for-note homophony in the first section” (Trial 2019)' },
  'texture.type:Monophonic': { d: 'A single melodic line with no accompaniment — whether one player or many in unison.', e: '“a monophonic texture, where the cello has the only melodic role” (HSC 2021); “the piece begins monophonically” (Trial 2021)' },
  'texture.type:Polyphonic': { d: 'Two or more independent melodic lines sounding at once, each keeping its own shape.', e: '“each voice has individual importance, creating polyphonic texture” (HSC 2016); “denser and more polyphonic” (HSC 2023); “elements of polyphony” (Trial 2021)' },
  'texture.type:Polyphony': { d: '', e: '“each voice has individual importance, creating polyphonic texture” (HSC 2016); “denser and more polyphonic” (HSC 2023); “elements of polyphony” (Trial 2021)' },
  'timbre.element:Timbre': { d: 'The quality that tells one instrument or voice from another sounding the same pitch at the same loudness.', e: '' },
  'timbre.warm:Cantabile': { d: '', e: '“from dolce… to con forza” (HSC 2020); “marked espressivo” (Trial 2025); “lyrical and cantabile” (Trial 2021)' },
}
