// GENERATED FILE — do not edit by hand.
//
// The vocabulary comes from two Notion databases under "Elements of Music —
// Vocabulary": **Vocabulary Fields** (the shape — one row per sub-list, with
// its concept, its stable field id and its position) and **Vocabulary Terms**
// (the words — one row is one word, related to its field, ticked if it tags
// itself, with any alternative spellings). The concepts, their order and the
// eight hues come from scripts/sync-vocabulary.mjs. Change a word in Notion,
// or the shape in that script, then run:
//
//   npm run sync:vocab
//
// See lib/musicElements.ts for what ELEMENTS feeds, and lib/propertyTags.ts
// for what AUTO_TERMS and ALIASES do.
import type { ElementCategory } from './musicElements'

export const ELEMENTS: ElementCategory[] = [
  {
    id: 'pitch',
    color: '#f87171',
    label: 'Pitch',
    fields: [
      {
        id: 'pitch.contour',
        label: 'Melodic motion & contour',
        options: [
          'Angular',
          'Arc-shaped',
          'Ascending',
          'Conjunct',
          'Contour',
          'Contrary motion',
          'Descending',
          'Disjunct',
          'Florid',
          'Leap',
          'Parallel motion',
          'Sequence',
          'Sequential',
          'Similar motion',
          'Smooth',
          'Static',
          'Stepwise',
          'Virtuosic',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.range',
        label: 'Range & register',
        options: [
          'High register',
          'Limited range',
          'Low register',
          'Narrow range',
          'Register extremes',
          'Tessitura',
          'Wide range',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.tonality',
        label: 'Tonality',
        options: [
          'Bitonal',
          'Chromatic',
          'Chromaticism',
          'Diatonic',
          'Major',
          'Minor',
          'Modal',
          'Modality',
          'Modulating',
          'Picardy 3rd',
          'Polytonal',
          'Tierce de picardie',
          'Tonal',
          'Tonal ambiguity',
          'Tonal centre',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.scale',
        label: 'Scale / mode type',
        options: [
          'Aeolian',
          'Chromatic scale',
          'Dorian',
          'Harmonic minor',
          'Mixolydian',
          'Pentatonic',
          'Phrygian',
          'Scale-based',
          'Scalic',
          'Whole-tone',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.harmony',
        label: 'Harmony & chord quality',
        options: [
          'Arpeggiated',
          'Augmented',
          'Block chords',
          'Broken chords',
          'Diminished',
          'Drone',
          'Inverted',
          'Major 7',
          'Open 5ths',
          'Pedal point',
          'Quartal',
          'Resolution',
          'Resolved',
          'Root position',
          'Suspended',
          'Suspension',
          'Tonic-and-dominant based',
          'Triadic',
          'Unresolved',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.consonance',
        label: 'Consonance / dissonance',
        options: [
          'Cluster-like',
          'Clusters',
          'Consonant',
          'Dissonance',
          'Dissonant',
          'Semitone dissonance',
        ],
        allowCustom: true,
      },
      {
        id: 'pitch.cadence',
        label: 'Cadence type',
        options: ['Cadential', 'Imperfect', 'Perfect'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'duration',
    color: '#eab308',
    label: 'Duration',
    fields: [
      {
        id: 'duration.tempo',
        label: 'Speed (tempo)',
        options: ['Fast', 'Lively', 'Quick', 'Rapid', 'Slow'],
        allowCustom: true,
      },
      {
        id: 'duration.tempoChange',
        label: 'Tempo change',
        options: ['Acceleration', 'Getting faster', 'Slowing'],
        allowCustom: true,
      },
      {
        id: 'duration.drive',
        label: 'Drive / momentum',
        options: [
          'Boisterous',
          'Busy',
          'Driving',
          'Energetic',
          'Momentum',
          'Perpetual',
          'Propelling',
          'Relentless',
          'Rhythmic drive',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.steadiness',
        label: 'Steadiness / regularity',
        options: [
          'Balanced',
          'Consistent',
          'Constant',
          'Continuous',
          'Even',
          'Maintained',
          'Pervasive',
          'Regular',
          'Steady',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.syncopation',
        label: 'Irregularity / syncopation',
        options: [
          'Ambiguous',
          'Cross-rhythm',
          'Displaced',
          'Hemiola',
          'Hemiolic',
          'Off-beat',
          'Polyrhythm',
          'Polyrhythmic',
          'Shifting',
          'Syncopated',
          'Uneven',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.metre',
        label: 'Metre & metre changes',
        options: [
          'Changing metre',
          'Compound',
          'Duple',
          'Mixed metre',
          'Multimetric',
          'Quadruple',
          'Simple triple',
          'Triple',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.values',
        label: 'Note-value character',
        options: [
          'Anacrusis',
          'Augmentation',
          'Augmented',
          'Diminution',
          'Dotted',
          'Duplet',
          'Long',
          'Quintuplet',
          'Sextuplet',
          'Short',
          'Shorter',
          'Snap',
          'Sustained',
          'Tied',
          'Triplet',
        ],
        allowCustom: true,
      },
      {
        id: 'duration.feel',
        label: 'Rhythmic feel & character',
        options: ['Chant-like', 'Dance-like', 'Lilting', 'March-like', 'Stamping', 'Warlike'],
        allowCustom: true,
      },
      {
        id: 'duration.italian',
        label: 'Tempo & rhythmic terms (Italian)',
        options: [
          'Accelerando',
          'Allegretto grazioso',
          'Allegro',
          'Allegro Vivace',
          'Animando',
          'Leggierissimo',
          'Lento',
          'Lento maestoso',
          'Maestoso',
          'Metric modulation',
          'Moto perpetuo',
          'Rallentando',
          'Ritardando',
          'Ritenuto',
          'Rubato',
          'Senza misura',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'dynamics',
    color: '#22c55e',
    label: 'Dynamics',
    fields: [
      {
        id: 'dynamics.volume',
        label: 'Dynamic level',
        options: ['ppp', 'pp', 'p', 'mp', 'mf', 'f', 'ff', 'fff'],
        allowCustom: true,
      },
      {
        id: 'dynamics.loudness',
        label: 'Loudness level',
        options: [
          'Forced',
          'Limited',
          'Loud',
          'Quiet',
          'Soft',
          'Softer',
          'Static (volume)',
          'Subtle',
          'Wide (dynamic range)',
        ],
        allowCustom: true,
      },
      {
        id: 'dynamics.change',
        label: 'Change in dynamics',
        options: [
          'Frequent',
          'Gradual',
          'Gradually',
          'Sudden',
          'Swelling',
          'Swells',
          'Terraced',
          'Varied',
        ],
        allowCustom: true,
      },
      {
        id: 'dynamics.italian',
        label: 'Dynamic markings (Italian)',
        options: [
          'Crescendo',
          'Decrescendo',
          'Diminuendo',
          'Dynamic letter levels (ppp–ff)',
          'Fortepiano (fp)',
          'Sforzando (sfz)',
          'Sfzp',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'expressive',
    color: '#84cc16',
    label: 'Expression',
    fields: [
      {
        id: 'expressive.articulation',
        label: 'Articulation',
        options: [
          'Accented',
          'Arco',
          'Detached',
          'Legato',
          'Marcato',
          'Pizzicato',
          'Slurred',
          'Slurs',
          'Staccatissimo',
          'Staccato',
          'Sustained',
          'Tenuto',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.technique',
        label: 'Special playing techniques',
        options: [
          'Bartók pizz.',
          'Col legno',
          'Glissandi',
          'Glissando',
          'Jeté bowing',
          'Laissez vibrer',
          'Slap tonguing',
          'Snap pizzicato',
          'Spiccato',
          'Sul ponticello',
          'Sul tasto',
          'Tremolo',
          'Trill',
          'Vibrato',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.phrasing',
        label: 'Phrasing & character',
        options: [
          'Animated (animando)',
          'Barbaric (feroce)',
          'Boisterous',
          'Delicate',
          'Dramatic',
          'Energetic',
          'Expressive',
          'Forceful',
          'Graceful',
          'Intense',
          'Languid',
          'Lyrical',
          'Majestic (maestoso)',
          'Playful',
          'Relentless',
          'Savage',
          'Sweet (dolce)',
          'Urgent',
        ],
        allowCustom: true,
      },
      {
        id: 'expressive.italian',
        label: 'Performance directions (Italian)',
        options: [
          '‘Breathing’ marks',
          'Ad libitum',
          'Cantabile',
          'Con forza',
          'Con sordino (mute)',
          'Delicatamente',
          'Dolce',
          'Espressivo',
          'Grazioso',
          'Leggierissimo',
          'Leggiero',
          'Semplice',
          'Senza misura',
          'Senza sordino',
          'Senza vibrato',
          'Sotto voce',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'media',
    color: '#60a5fa',
    label: 'Performing media',
    fields: [
      {
        id: 'media.instrument',
        label: 'Instrument / section',
        options: [
          'Brass',
          'Guitar',
          'Keyboard',
          'Percussion',
          'Strings',
          'Synth / electronic',
          'Voice',
          'Woodwind',
        ],
        allowCustom: true,
      },
      {
        id: 'media.ensemble',
        label: 'Ensemble / forces',
        options: [
          'A cappella',
          'Big band',
          'Chamber ensemble',
          'Choir',
          'Concert band',
          'Duet',
          'Orchestra',
          'Quartet',
          'Quintet',
          'Rock band',
          'Solo',
          'String orchestra',
          'Trio',
          'Vocal ensemble',
        ],
        allowCustom: true,
      },
      {
        id: 'media.production',
        label: 'Sound produced by',
        options: ['Blowing', 'Bowing', 'Electronic', 'Plucking', 'Singing', 'Striking'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'timbre',
    color: '#22d3ee',
    label: 'Timbre',
    fields: [
      {
        id: 'timbre.bright',
        label: 'Bright / brilliant',
        options: [
          'Bright',
          'Brilliant',
          'Clear',
          'Crisp',
          'Glittering',
          'Ringing',
          'Shimmering',
          'Sparkling',
          'Vibrant',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.warm',
        label: 'Warm / mellow / smooth',
        options: [
          'Cantabile',
          'Ethereal',
          'Even',
          'Floating',
          'Fluid',
          'Gentle',
          'Lyrical',
          'Mellow',
          'Sweet',
          'Warm',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.dark',
        label: 'Dark / dull / heavy',
        options: ['Dark', 'Dull', 'Heavy', 'Hollow', 'Muted', 'Subdued'],
        allowCustom: true,
      },
      {
        id: 'timbre.harsh',
        label: 'Harsh / strident / forceful',
        options: [
          'Acute',
          'Brittle',
          'Forceful',
          'Harsh',
          'Intense',
          'Relentless',
          'Strident',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.material',
        label: 'Material / sound-source',
        options: [
          'Bell-like',
          'Dry',
          'Echoey',
          'Metallic',
          'Nasal',
          'Percussive',
          'Resonant',
          'Wooden',
          'Woody',
        ],
        allowCustom: true,
      },
      {
        id: 'timbre.mood',
        label: 'Mood / character',
        options: ['Delicate', 'Dramatic', 'Eerie', 'Languid', 'Playful'],
        allowCustom: true,
      },
      {
        id: 'timbre.density',
        label: 'Density',
        options: ['Full', 'Homogenous', 'Light', 'Rich', 'Thin', 'Transparent'],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'texture',
    color: '#a78bfa',
    label: 'Texture',
    fields: [
      {
        id: 'texture.type',
        label: 'Texture type',
        options: ['Contrapuntal', 'Homophonic', 'Monophonic', 'Polyphonic', 'Polyphony'],
        allowCustom: true,
      },
      {
        id: 'texture.role',
        label: 'Layer role',
        options: [
          'Accompaniment',
          'Bass line',
          'Counter-melody',
          'Melody',
          'Pad / drone',
          'Rhythmic',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.layers',
        label: 'Layer relationship & count',
        options: [
          'Block (chordal)',
          'Dialogue',
          'Doubled',
          'Doubling',
          'Independent',
          'Interplay',
          'Layered',
          'Layers',
          'Single line',
          'Unison (as texture)',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.density',
        label: 'Density',
        options: [
          'Busy',
          'Complex',
          'Dense',
          'Density',
          'Full',
          'Light',
          'Lighter',
          'Rich',
          'Sparse',
          'Thick',
          'Thicken',
          'Thin',
        ],
        allowCustom: true,
      },
      {
        id: 'texture.devices',
        label: 'Compositional-device textures',
        options: [
          'Antiphonal',
          'Canon',
          'Canonic',
          'Countermelody',
          'Fugal',
          'Fugue-like',
          'Hocket',
          'Imitation',
          'Imitative',
          'Interlocking',
          'Staggered entries',
        ],
        allowCustom: true,
      },
    ],
  },
  {
    id: 'structure',
    color: '#f97316',
    label: 'Structure',
    fields: [
      {
        id: 'structure.phrase',
        label: 'Phrase & form shape',
        options: [
          'Arc-shaped',
          'Arch',
          'Cadenza',
          'Call-and-response',
          'Climactic',
          'Climax',
          'Coda',
          'Codetta',
          'Question-and-answer',
          'Sectional',
          'Sections',
          'Theme and variations',
          'Through-composed',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.repetition',
        label: 'Repetition & recurring material',
        options: ['Echoed', 'Mirrored', 'Ostinato', 'Recurring', 'Repeated', 'Repetition'],
        allowCustom: true,
      },
      {
        id: 'structure.development',
        label: 'Development of ideas',
        options: [
          'Augmented',
          'Developed',
          'Development',
          'Diminution',
          'Elaborated',
          'Extended',
          'Extension',
          'Fragmentation',
          'Fragmented',
          'Inversion',
          'Inverted',
          'Motif',
          'Motivic',
          'Sequence',
          'Sequential',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.imitation',
        label: 'Imitative / canonic devices',
        options: [
          'Antiphonal',
          'Canon',
          'Canonic',
          'Fugal',
          'Fugue-like',
          'Imitation',
          'Imitative',
          'Staggered',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.contrast',
        label: 'Contrast / variety',
        options: [
          'Alternating',
          'Contrasting',
          'Juxtaposed',
          'Variation',
          'Varied',
          'Variety',
        ],
        allowCustom: true,
      },
      {
        id: 'structure.unity',
        label: 'Unity / cohesion',
        options: ['Consistent', 'Return', 'Returning', 'Unified', 'Unifying', 'Unity'],
        allowCustom: true,
      },
      {
        id: 'structure.balance',
        label: 'Balance & symmetry',
        options: ['Balance', 'Balanced', 'Even phrase length', 'Symmetrical'],
        allowCustom: true,
      },
    ],
  },
]

/**
 * Words that tag themselves as you type — the Auto-tag tick in Notion.
 * Only words nobody writes in their everyday sense belong here; "even",
 * "light" and "major" are deliberately absent.
 */
export const AUTO_TERMS: string[] = [
  'Accelerando',
  'Accented',
  'Aeolian',
  'Allegro',
  'Anacrusis',
  'Animando',
  'Antiphonal',
  'Arc-shaped',
  'Arco',
  'Arpeggiated',
  'Ascending',
  'Augmentation',
  'Augmented',
  'Bell-like',
  'Bitonal',
  'Blowing',
  'Bowing',
  'Brass',
  'Cadential',
  'Cadenza',
  'Call-and-response',
  'Canon',
  'Canonic',
  'Cantabile',
  'Chant-like',
  'Choir',
  'Chromatic',
  'Chromaticism',
  'Climactic',
  'Cluster-like',
  'Clusters',
  'Coda',
  'Codetta',
  'Compound',
  'Conjunct',
  'Consonant',
  'Contrapuntal',
  'Counter-melody',
  'Countermelody',
  'Crescendo',
  'Cross-rhythm',
  'Dance-like',
  'Decrescendo',
  'Delicatamente',
  'Descending',
  'Diatonic',
  'Diminished',
  'Diminuendo',
  'Diminution',
  'Disjunct',
  'Dissonance',
  'Dissonant',
  'Dolce',
  'Dorian',
  'Dotted',
  'Drone',
  'Duet',
  'Duple',
  'Duplet',
  'Echoey',
  'Espressivo',
  'Ethereal',
  'Florid',
  'Fugal',
  'Fugue-like',
  'Glissandi',
  'Glissando',
  'Grazioso',
  'Hemiola',
  'Hemiolic',
  'Hocket',
  'Homogenous',
  'Homophonic',
  'Imitation',
  'Imitative',
  'Imperfect',
  'Legato',
  'Leggierissimo',
  'Leggiero',
  'Lento',
  'Lilting',
  'Lyrical',
  'Maestoso',
  'Marcato',
  'March-like',
  'Mellow',
  'Metallic',
  'Mixolydian',
  'Modal',
  'Modality',
  'Modulating',
  'Monophonic',
  'Motivic',
  'Multimetric',
  'Nasal',
  'Off-beat',
  'Orchestra',
  'Ostinato',
  'Pentatonic',
  'Percussion',
  'Percussive',
  'Phrygian',
  'Pizzicato',
  'Plucking',
  'Polyphonic',
  'Polyphony',
  'Polyrhythm',
  'Polyrhythmic',
  'Polytonal',
  'Quadruple',
  'Quartal',
  'Quartet',
  'Question-and-answer',
  'Quintet',
  'Quintuplet',
  'Rallentando',
  'Ritardando',
  'Ritenuto',
  'Rubato',
  'Scale-based',
  'Scalic',
  'Sectional',
  'Semplice',
  'Sequential',
  'Sextuplet',
  'Sfzp',
  'Slurred',
  'Slurs',
  'Spiccato',
  'Staccatissimo',
  'Staccato',
  'Stepwise',
  'Syncopated',
  'Tenuto',
  'Terraced',
  'Tessitura',
  'Through-composed',
  'Tonal',
  'Tremolo',
  'Triadic',
  'Trill',
  'Trio',
  'Triple',
  'Triplet',
  'Unresolved',
  'Vibrato',
  'Warlike',
  'Whole-tone',
  'Woodwind',
]

/**
 * Alternative spellings prose is recognised by, mapped to the word they
 * stand for — the Aliases column. Irregular forms only: the regular
 * English ones are generated in propertyTags.ts and need no row here.
 */
export const ALIASES: Record<string, string> = {
  'arpeggio': 'Arpeggiated',
  'arpeggios': 'Arpeggiated',
  'cadence': 'Cadential',
  'cadences': 'Cadential',
  'cresc': 'Crescendo',
  'cresc.': 'Crescendo',
  'fugue': 'Fugue-like',
  'fugues': 'Fugue-like',
  'motifs': 'Motif',
  'motives': 'Motif',
  'pizz': 'Pizzicato',
  'pizz.': 'Pizzicato',
  'rit.': 'Ritardando',
  'ritard.': 'Ritardando',
  'sequences': 'Sequence',
}
